apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: public.ecr.aws/docker/library/alpine:latest
        imagePullPolicy: Always
        command: ["/bin/ash"]
        args: [ "-c", "apk add ipmitool curl iperf3; sleep infinity"]
        name: alpine
        volumeMounts:
          - name: hostroot
            mountPath: /host
        securityContext:
          privileged: true
          runAsUser: 0
      volumes:
        - name: hostroot
          hostPath:
            path: /

            apiVersion: v1
kind: Pod
metadata:
  name: alpine-root
  annotations:
spec:
  #  nodeSelector:
  #    kubernetes.io/hostname: master-0
  hostNetwork: true
  containers:
    - image: alpine
      command: ["/bin/ash"]
      args: [ "-c", "apk add iperf3; iperf3 -s"]
      imagePullPolicy: IfNotPresent
      name: alpine
      volumeMounts:
        - name: hostroot
          mountPath: /host
      securityContext:
        privileged: true
        runAsUser: 0
  volumes:
    - name: hostroot
      hostPath:
        path: /
